### ISSUE TITLE
change suggestion.

### ISSUE THREAD

**Issue by amqndin** [finndotbin/datapack-conventions#1]
i have a problem with naming conventions, i dont think putting an underscore in front of internal functions is the way here, i'd say the opposite would be much better here. my reasoning is that if you put an underscore in function's name its going to show up at the very top in autocompletion, so if we make public functions have underscore, they would show up at the very top in autocompletion making it easy to find, and private functions are unseen, at the bottom of the autocompletion. that logic is also good in the explorer since files are sorted in alphabetic order.

**Comment by finndotbin** [comment]
i agree. having items be private by default could be useful as most items are going to be private anyway. i'll think this over a little more and talk about it with others before i fully commit to the change though. thank you for the feedback.

**Comment by finndotbin** [comment]
alright i changed it. thanks for the suggestion :D
